### ISSUE TITLE
mutex lock bug

### ISSUE THREAD

**Issue by j123123** [tongram/ton#1]
bug: https://govnokod.ru/25999#comment510267
https://github.com/tongram/ton/blob/536d37830b10d0a1aeac97db72a7f6569e177a88/blockchain-explorer/blockchain-explorer.cpp#L96-L117

**Comment by twepl** [comment]
Ха ору от комментов :)
>То есть они два раза из одного треда вызывают std::mutex::lock()? Охуенные там ДОКТОРА НАУК код пишут.

Ну бывает парень ошибся, не критично, если нужно исправить кидай пул реквест внесу изменения.
Я уверен что там много косяков в коде.
